# Generated by Django 4.2.2 on 2023-06-28 14:46

import django.core.validators
from django.db import migrations, models
import outgoings.models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='outgoingscategory',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='outgoingscategory',
            name='total',
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='day_of_month',
            field=outgoings.models.DayOfMonthField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
