# Generated by Django 4.2.2 on 2023-07-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outgoings', '0002_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingscategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
